@echo off

echo x=msgbox("Your computer..." ,0, "Microsoft Windows") >> msgbox.vbs

start msgbox.vbs


echo x=msgbox("Failed to delete VMWARE > system32" ,2, "Error") >> WAA.vbs

start WAA.vbs

echo x=msgbox("MUAHAHAHAHHA" ,0, "Microsoft Windows") >> lastwords.vbs

start lastwords.vbs

start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs
start lastwords.vbs